apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx3-pipeline-catalog
      changes:
        - regex:
            pattern: "jenkins-x/jx-updatebot:(.*)"
            files:
              - "**/*.yaml"
    - urls:
        - https://github.com/jenkins-x-charts/jxboot-helmfile-resources
      changes:
        - regex:
            pattern: "updatebot: (.*)"
            files:
              - "charts/jxboot-helmfile-resources/values.yaml"
