apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx3-pipeline-catalog
      changes:
        - regex:
            pattern: "jenkinsxio/jx-updatebot:(.*)"
            files:
              - "**/*.yaml"
    - urls:
        - https://github.com/jenkins-x/jx3-versions
      changes:
        - regex:
            pattern: "version: (.*)"
            files:
              - "docker/gcr.io/jenkinsxio/jx-updatebot.yml"
