apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - changes:
        - go:
            owner:
              - jenkins-x-plugins
            repositories:
              include:
                - "*"
            package: github.com/jenkins-x/jx-api
            upgradePackages:
              include:
                - "github.com/jenkins-x/*"
                - "github.com/jenkins-x-plugins/*"
